# alertmanager-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  type: NodePort
  selector:
    alertmanager: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      nodePort: 30093

