apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-alertmanager
  namespace: default
  labels:
    app: alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'discord'
      routes:
        - match:
            ai_alert: "true"
          receiver: 'discord'
        - match_re:
            severity: "critical|warning"
          receiver: 'discord'

    receivers:
      - name: 'discord'
        webhook_configs:
          - url: 'https://discord.com/api/webhooks/1234567890/abcdEfGhIjKlMnOpQrStUvWxYz'
            send_resolved: true

    templates:
      - '/etc/alertmanager/config/*.tmpl'
